const state = {
    userInfo:{},
    crumbs:[],
    navgationData:[
        {
            title:'部件管理',
            sub:[
                {title:'部件列表',page:'PartsManageHome'}
            ]
        },
        {
            title:'商品管理',
            sub:[
                {title:'商品列表',page:'Products'}
            ]
        },

        {
            title:'工艺路线',
            sub:[
                {title:'工艺列表',page:'ProcessRoute'},
                {title:'工艺列表1',
                    sub:[
                        {title:'三级列表1'}
                    ]
                }
            ]
        },
        {
            title:'物料管理',
            sub:[
                {title:'木材',page:'MaterialMannage'}
            ]
        },
        {
            title:'基础设置',
            sub:[
                {title:'物料分类字段',page:'Materialfield'},
                {title:'工艺属性字段',page:'Technology'},
                {title:'工序分类字段',page:'Process'},
                {title:'产品分类字段',page:'Productfield'},
                {title:'测量字段',page:'Measure'},
                {title:'部件字段',page:'Partfield'},
            ]
        },
        {
            title:'人员管理',
            sub:[
                {title:'用户管理',page:'PersonnelManagementUser'},
                {title:'角色管理',page:'PersonnelManagementRole'},
            ]
        }
    ]
}

export default state